Codecov demoted to amber, expand on what coverage reporting _is_.
UCL-ARC/python-tooling pull request #288
Opened 2024-01-24 15:26 UTC by samcunliffe

Solves #254

2024-01-24 15:37 UTC, dstansby requested changes
I disagree about moving codecov to amber - although it can be a bit flaky sometimes, unless we can recommend a *better* tool I think it should stay green.

For reference our [guidance on amber is:](https://github-pages.arc.ucl.ac.uk/python-tooling/#traffic-lights)

> 🟠 We don’t discourage using this, but it may duplicate functionality of a green tool.

2024-01-24 15:38 UTC, paddyroddy approved these changes

2024-01-24 15:39 UTC, paddyroddy commented
> I disagree about moving codecov to amber - although it can be a bit flaky sometimes, unless we can recommend a _better_ tool I think it should stay green.

Without being a bag, we discussed various points in person yesterday. Would have been good if you were able to join these, consider it already "decided".

🫐

2024-01-24 15:40 UTC, dstansby commented
And FWIW I think codecov should be green above coveralls, because you can use codecov with private repos for free ([see their pricing](https://about.codecov.io/pricing/)), but can't use coveralls with private repos for free ([see their pricing](https://coveralls.io/pricing))

2024-01-24 15:41 UTC, dstansby commented
> > I disagree about moving codecov to amber - although it can be a bit flaky sometimes, unless we can recommend a _better_ tool I think it should stay green.
> 
> Without being a nag, we discussed various points in person yesterday. Would have been good if you were able to join these, consider it already "decided".

This is totally not fair - stuff shouldn't be discussed in person, that discussion not documented, and others not able to challenge or question it afterwards just because they weren't in the room.

2024-01-24 15:43 UTC, samcunliffe commented
Why did we decide it should go 🟠 ? Was it just because slow and a little flakey?

Perhaps it _should_ stay green because it's widely used (by us).

In answer to a question (maybe mine) from yesterday...
[We generate coverage reports](https://github.com/UCL-ARC/python-tooling/blob/main/%7B%7Bcookiecutter.project_slug%7D%7D/pyproject.toml#L124) but we don't [upload anywhere](https://github.com/UCL-ARC/python-tooling/blob/main/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/tests.yml#L44).

2024-01-24 15:44 UTC, samcunliffe commented
> And FWIW I think codecov should be green above coveralls, because you can use codecov with private repos for free ([see their pricing](https://about.codecov.io/pricing/)), but can't use coveralls with private repos for free ([see their pricing](https://coveralls.io/pricing))

This would also convince me. Not all research software projects are open.

2024-01-24 15:44 UTC, dstansby commented
> > > I disagree about moving codecov to amber - although it can be a bit flaky sometimes, unless we can recommend a _better_ tool I think it should stay green.
> > 
> > 
> > Without being a nag, we discussed various points in person yesterday. Would have been good if you were able to join these, consider it already "decided".
> 
> This is totally not fair - stuff shouldn't be discussed in person, that discussion not documented, and others not able to question it afterwards just because they weren't in the room.

2024-01-24 15:56 UTC, paddyroddy commented
> Why did we decide it should go 🟠 ? Was it just because slow and a little flakey?

I _think_ it was because we were claiming we can only have 🟢 and the tools were considered as good as each other. Personally, I've had fewer issues with `coveralls` over `codecov` - in terms of flaky-ness.

2024-01-24 15:57 UTC, paddyroddy commented
> This is totally not fair - stuff shouldn't be discussed in person, that discussion not documented, and others not able to challenge or question it afterwards just because they weren't in the room.

I see your point, but we wouldn't achieve much if literally everything discussed had to be documented. Unless we had someone taking minutes.

2024-01-24 16:04 UTC, dstansby commented
> I see your point, but we wouldn't achieve much if literally everything discussed had to be documented. Unless we had someone taking minutes.

I think in the interests of being an open and collaborative project reasons for decisions should at least be written down somewhere.

2024-01-24 16:07 UTC, dstansby commented
> I _think_ it was because we were claiming we can only have 🟢 and the tools were considered as good as each other. Personally, I've had fewer issues with `coveralls` over `codecov` - in terms of flaky-ness.

I haven't used coveralls in ages, so could believe it's less flaky.

Another point in favour of codecov is that it's more widely used by big OSS scientific Python projects (AFAIK)?

2024-01-24 17:14 UTC, samcunliffe commented
I'm convinced to put these comments into the page. I've not got a strong feeling about 🟢 or 🟠 .

2024-01-24 18:08 UTC, matt-graham commented
> I'm convinced to put these comments into the page. I've not got a strong feeling about 🟢 or 🟠 .

I also have no opinion on 🟢 versus 🟠 but I strongly agree with @samcunliffe's suggestion to put the details discussed here comparing Codecov / Coveralls in the table / on the page, particularly @dstansby points about being able to use Codecov with private repositories, and that Codecov appears to be more widely used by major Scientific Python packages (from a quick scan of repositories, all of NumPy, Matplotlib and pandas appear to use Codecov).

2024-01-24 18:13 UTC, matt-graham commented
> This is totally not fair - stuff shouldn't be discussed in person, that discussion not documented, and others not able to challenge or question it afterwards just because they weren't in the room.

> I think in the interests of being an open and collaborative project reasons for decisions should at least be written down somewhere.

I also think @dstansby points here are very valid and given we've been explicitly discussing how we might encourage getting outside contributors, making sure we have processes which make sure everyone can equally contribute to discussions is important.

2024-01-24 18:14 UTC, paddyroddy commented
> I also think @dstansby points here are very valid and given we've been explicitly discussing how we might encourage getting outside contributors, making sure we have processes which make sure everyone can equally contribute to discussions is important.

I agree, but it is very easy to say without actually doing anything. The only way for that to actually happen is someone to spend the whole time taking minutes, or recording the whole thing. I would not volunteer for either of those roles.

2024-01-24 18:19 UTC, matt-graham commented
> I agree, but it is very easy to say without actually doing anything. The only way for that to actually happen is someone to spend the whole time taking minutes, or recording the whole thing. I would not volunteer for either of those roles.

I don't think we need minutes, we just need to make sure if we have an off-GitHub discussion (be it in-person or on Slack) and this leads to an issue being raised around some decision point about a change to be made we record the key points of the discussion and why the decision was made.

2024-01-24 18:20 UTC, paddyroddy commented
> I don't think we need minutes, we just need to make sure if we have an off-GitHub discussion (be it in-person or on Slack) and this leads to an issue being raised around some decision point about a change to be made we record the key points of the discussion and why the decision was made.

Yes, but to remember those points...

2024-01-24 18:30 UTC, matt-graham commented
> Yes, but to remember those points...

If we are recording the points in the initial issue comment as we create an issue I don't think there should be a problem remembering them.

For example if we're creating issues in a discussion / planning session like we had in the first part of yesterday morning, I think the extra overhead of having someone (probably distinct from the person leading the planning) note down any key points discussed would be minimal. And this would also have the additional benefit of making it easier to understand why decisions were made previously if we subsequently review and decided to change.

2024-01-24 18:33 UTC, paddyroddy commented
> If we are recording the points in the initial issue comment as we create an issue I don't think there should be a problem remembering them.

Sounds like a plan.

2024-01-24 18:38 UTC, matt-graham commented
Sorry realise this went quite off-topic but I though it was a useful discussion to have. I'll create a new issue to remind us to somehow agree on and document a process around this.

2024-01-24 18:43 UTC, dstansby commented
Yeah, to be clear not looking for full discussion notes or anything, just a brief summary of why a decision has been made so it's clear to anyone who wasn't part of the discussion. For this PR, some summary notes in the body of https://github.com/UCL-ARC/python-tooling/issues/254 were what I was expecting.

2024-01-25 10:09 UTC, samcunliffe commented
Still not a strong opinion, but I think two 🟠 is probably an accurate representation of the situation. We don't have a consensus about which is better. And we don't have either implemented in our template.

2024-01-25 10:10 UTC, dstansby commented
In that case I'd say have two 🟢 ? I think it's better to have at least one green per category, otherwise we run the risk of people not choosing anything if there's just 🟠 ?

2024-01-25 10:11 UTC, dstansby commented
But also, as I've said above codecov 1) can be used for private repos 2) is more widely used across scipy ecosystem, and I still think that's enough to edge out coveralls unless anyone has any other arguments for coveralls above codecov?

2024-01-25 10:13 UTC, samcunliffe commented
> But also, as I've said above codecov 1) can be used for private repos 2) is more widely used across scipy ecosystem, and I still think that's enough to edge out coveralls unless anyone has any other arguments for coveralls above codecov?

Should we go all in and add it to the template's CI? (+ a badge, obvs.)

2024-01-25 11:05 UTC, paddyroddy commented
> But also, as I've said above codecov 1) can be used for private repos 2) is more widely used across scipy ecosystem, and I still think that's enough to edge out coveralls unless anyone has any other arguments for coveralls above codecov?

Flakiness, from my own experience

2024-01-25 11:07 UTC, paddyroddy commented
> Should we go all in and add it to the template's CI? (+ a badge, obvs.)

That would be good, but it's another thing they would need to set up #205

2024-01-25 12:20 UTC, dstansby approved these changes

2024-01-25 12:20 UTC, dstansby commented on docs/pages/ci.md
> +| [Codecov](https://docs.codecov.com/docs) | Hosted service to report code coverage metrics. Occasionally slow to update after a report is updated, can be configured to add extra CI checks. This serv
```suggestion
| [Codecov](https://docs.codecov.com/docs) | Hosted service to report code coverage metrics. Occasionally slow to update after a report is updated, can be configured to add extra CI checks. This service is probably more widely used and is [free for both open-source and private projects](https://about.codecov.io/pricing/). | 🟢   |
```

2024-01-25 12:20 UTC, dstansby commented on docs/pages/ci.md
> +| [Coveralls](https://docs.coveralls.io/)  | Hosted service to report code coverage metrics. ery similar to codecov and we don't strongly recommend one over the other. This service is only [free for
```suggestion
| [Coveralls](https://docs.coveralls.io/)  | Hosted service to report code coverage metrics. Very similar to codecov and we don't strongly recommend one over the other. This service is only [free for open-source projects](https://coveralls.io/pricing).                                                                         | 🟢   |
```

2024-01-25 12:21 UTC, dstansby commented
> Flakiness, from my own experience

Ah fair enough, sorry for forgetting/not reading properly. I'm still pro both as green? Won't block this PR if others think both amber though

2024-02-06 10:38 UTC, dstansby commented
I'd be happy to merge this if the amber > green change is made

2024-02-06 10:58 UTC, samcunliffe commented
I've updated the PR title and commit message to reflect our decision.

2024-02-06 11:05 UTC, merged

2024-02-22 15:47 UTC, paddyroddy commented
https://hynek.me/articles/ditch-codecov-python

2024-02-29 15:27 UTC, samcunliffe commented
For those who can access it, we did a very lightweight solution over in INFORMus.
https://github.com/inform-us/INFORMus/blob/dev/.github/workflows/api.yml#L49-L75

And it's working well so far.

Using
* https://github.com/irongut/CodeCoverageSummary (which can fail CI if coverage is too low)
* https://github.com/marocchino/sticky-pull-request-comment (for posting bot comments 🤖 )