Minor improvements to templates page
UCL-ARC/python-tooling pull request #333
Opened 2024-03-25 17:05 UTC by dstansby

- "Domain" > "Community" specific templates
- This makes the first sentence redundant, so remove
- Fix some tool names

2024-03-25 17:23 UTC, samcunliffe requested changes
Thanks 👍

2024-03-25 17:23 UTC, samcunliffe commented on docs/pages/templates.md
> +## Community specific templates
```suggestion
## Community-specific templates
```
(Compound adjective)

2024-03-25 17:23 UTC, samcunliffe commented on docs/pages/templates.md
> +| [Scikit-HEP](https://github.com/scikit-hep/cookie)                 | Cookiecutter template developed by SciKit-HEP.                                                         |
```suggestion
| [Scientific Python](https://github.com/scientific-python/cookie)                 | Cookiecutter template developed by [SciKit-HEP](https://github.com/scikit-hep) but now adapted by the more general Scientific Python community.                                                         |
```

Which will fail prettier, of course.

2024-03-26 10:07 UTC, dstansby commented on docs/pages/templates.md
> +| [Scikit-HEP](https://github.com/scikit-hep/cookie)                 | Cookiecutter template developed by SciKit-HEP.                                                         |
👍 done

2024-03-26 10:07 UTC, dstansby commented on docs/pages/templates.md
> +## Community specific templates
👍  done

2024-03-26 10:25 UTC, samcunliffe approved these changes
🫐

2024-03-26 10:25 UTC, merged